sonar.verbose=true
sonar.organization=siva-vipparla
sonar.projectKey=siva-vipparla_sweety
sonar.projectName=sweety
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
